apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sc-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix       
            backend:
              service:
                name: sc-frontend
                port: 
                  number: 80
          - path: /api
            pathType: Prefix       
            backend:
              service:
                name: sc-backend
                port: 
                  number: 8080
