apiVersion: v1
kind: Service
metadata:
  name: sc-backend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "websocket"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "wss"
spec:
  selector:
    app: sc-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sc-backend
  template:
    metadata:
      labels:
        app: sc-backend
    spec:
      containers:
        - name: sc-backend
          image: youjung819/sc_backend:2.0
          imagePullPolicy: Always
          command: ["sh", "-c", "echo The app is running! && sleep 3600"]
          ports:
            - containerPort: 3300
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_DATABASE
